version: "3.9"

services:
  dw_postgres:
    image: postgres:15
    container_name: dw_postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${DW_DB}
      POSTGRES_USER: ${DW_USER}
      POSTGRES_PASSWORD: ${DW_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DW_USER} -d ${DW_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  python_etl:
    build: ./etl
    container_name: python_etl
    env_file: .env
    depends_on:
      dw_postgres:
        condition: service_healthy


  mondrian:
    image: devopsappwilio/mondrian
    container_name: mondrian
    volumes:
      - ./mondrian:/schema
    ports:
      - "8081:8080"
    depends_on:
      dw_postgres:
        condition: service_healthy

  superset:
    image: apache/superset:3.0.1
    container_name: superset
    env_file: .env
    volumes:
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
      - superset_home:/app/superset_home
    ports:
      - "8088:8088"
    depends_on:
      dw_postgres:
        condition: service_healthy

volumes:
  postgres_data:
  superset_home:
